day_period_seconds: [270, 180, 210, 180]  # 四次缩圈时间段长度(秒)
deadly_nightrain_seconds: 110             # 雨中冒险持续时间(秒)

update_interval: 0.1  # 界面刷新间隔(秒)

# 自动检测间隔(秒)
detect_intervals:
  低: 0.5
  中: 0.2
  高: 0.1

foward_day_seconds: 10  # 快进一次缩圈时间（秒）
back_day_seconds: 10    # 后退一次缩圈时间（秒）

time_scale: 1.0   # 时间流逝倍率

template_standard_height: 30      # DAYX模板图片标准高度
mask_lower_white: [0, 0, 200]     # DAYX模板图片白色掩码下限(BGR)
mask_upper_white: [179, 90, 255]  # DAYX模板图片白色掩码上限(BGR)
scale_range: [0.8, 1.2, 20]       # DAYX模板匹配缩放范围(最小比例,最大比例,步数)
dayx_score_threshold: 0.8         # DAYX模板匹配得分阈值
dayx_detect_langs:                # DAYX模板匹配语言
  chs: '简体中文'
  cht: '繁體中文'
  eng: 'English'

upper_hls_not_in_rain: [3, 80, 128]   # 最高亮度下不在雨中时血条hls颜色
lower_hls_not_in_rain: [5, 52, 166]   # 最低亮度下不在雨中时血条hls颜色
upper_hls_in_rain: [163, 90, 130]     # 最高亮度下在雨中时血条hls颜色
lower_hls_in_rain: [164, 62, 173]     # 最低亮度下在雨中时血条hls颜色
h_tolerance: 5    # 血条颜色匹配色相容差
l_tolerance: 30   # 血条颜色匹配亮度容差
s_tolerance: 30   # 血条颜色匹配饱和度容差
hp_color_min_area_ratio: 0.1  # 血条颜色区域最小面积占比，小于此值视为无效
hp_color_max_area_ratio: 0.5  # 血条颜色区域最大面积占比，大于此值认为血条为对应颜色

fixed_map_overlay_draw_size: null     # 固定地图信息绘制尺寸(宽,高)
map_overlay_draw_size_ratio: 1.0      # 地图信息绘制尺寸相对于原图比例
full_map_error_threshold: 20          # 判断当前地图是否是完整地图的误差阈值
earth_shifting_error_threshold: 35    # 判断特殊地形的误差阈值
map_pattern_match_interval: 1800      # 自动地图匹配间隔(秒)

bug_report_email: "nroh-report@qq.com"

# 缩圈进度条样式
day_progress_css: |
  QProgressBar {
      border: 2px solid #5a5a5a;
      border-radius: {border_radius}px;
      background-color: rgba(60, 60, 60, 0.7);
      text-align: center;
  }
  QProgressBar::chunk {
      background-color: #9296cc;
  }

# 缩圈文字样式
day_text_css: |
  color: white; font-weight: bold; font-size: {font_size}px;

# 雨中冒险进度条样式
in_rain_progress_css: |
  QProgressBar {
      border: 2px solid #5a5a5a;
      border-radius: {border_radius}px;
      background-color: rgba(60, 60, 60, 0.7);
      text-align: center;
  }
  QProgressBar::chunk {
      background-color: #f766ba;
  }

# 雨中冒险文字样式
in_rain_text_css: |
  color: white; font-weight: bold; font-size: {font_size}px;
